import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import lit from "./lit";
import { useState } from "react";

const inter = Inter({ subsets: ['latin'] })


export default function Home() {

  const [file, setFile] = useState(null);


  async function handleEncryptString(){
    
    await lit.encryptString(); 
  }



  async function handleFileChange(event){
    console.log(event.target.files); 
    setFile(event.target.files[0]); 
  }

  async function handleEncryptFile(){
    console.log("*************EncryptFile***************"); 
    await lit.encryptFile(file); 
   // and also upload to encrypt file to web3storage
  }



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <input type="file" name="myImage" onChange={handleFileChange} />
      <button onClick={handleEncryptString}>encryptString and deCryptString</button>
      <button onClick={handleEncryptFile}>encryptFile</button>
      
    </>
  )
}
